# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8'
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Karly-K Prod(a11b3a3f-05ef-42b3-887f-759850e88bb0)'
    command: 'publish'
    publishWebProjects: false
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Karly-K Prod(a11b3a3f-05ef-42b3-887f-759850e88bb0)'
    appType: 'webApp'
    appName: 'BananaMan'
    package: '$(System.DefaultWorkingDirectory)/**/site.zip'
    deploymentMethod: 'zipDeploy'
